---
- name: codis environment init
  hosts: all
  remote_user: codis
  roles:
    - common

- name: Install codis-dashboard
  hosts: codis-dashboard-servers
  remote_user: codis
  roles:
    - codis-dashboard

- name: Install codis-proxy
  hosts: codis-proxy-servers
  remote_user: codis
  roles:
    - codis-proxy

- name: Install codis-server
  hosts: codis-servers
  remote_user: codis
  roles:
    - codis-server

- name: Install redis-sentinel
  hosts: redis-sentinel-servers
  remote_user: codis
  roles:
    - redis-sentinel

- name: Install codis-fe
  hosts: codis-fe-servers
  remote_user: codis
  roles:
    - codis-fe
